name: Linux build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Nmap
        run: sudo apt-get install nmap

      - name: Installing mocha globally
        run: npm install -g mocha

      - name: Test
        run:  npm test